name: my-appCI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: dddd
        run: ssh -i ${{ secrets.SSH_KEY }} root@15.164.84.222 mkdir . /home/ubuntu/f/deploy.sh
