name: my-appCI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: generage key file
        run: echo ${{ secrets.SSH_KEY }} > /tmp/key

      - name: dgenerage key file
        run: chmod 400 /tmp/key        

      - name: dddd
        run: ssh -i /tmp/key root@15.164.84.222 mkdir . /home/ubuntu/f/deploy.sh
